const strings = {
  myCashCoupon: 'My Cash Coupon',
  email: 'Email address',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  loginButton: 'Login',
  forgotPassword: 'Forgot password?',
  stillWithout: 'Still without account?',
  createOne: 'Create one',
  signup: 'Sign up',
  signupSubTitle: 'Start converting coupons to cash',
  name: 'Name',
  mobile: 'Mobile',
  username: 'User Name',
  alreadyAccount: 'I already have an account.',
  history: 'History',
  cashbackStores: 'Cashback Stores',
  balance: 'Balance',
  rs: '₹',
  welcomeBack: 'Welcome back to My Cash Coupon',
  withdraw: 'Withdraw',
  topCashback: 'TOP Cashback Stores',
  invalidEmail: 'Please enter valid email',
  invalidName: 'Please enter Name',
  invalidUsername: 'Please enter Username',
  invalidPassword: 'Please enter password',
  invalidMobile: 'Please enter Mobile number',
  mobileLength: 'Please enter 10 digit Mobile number',
  cancel: 'Cancel',
  logout: 'Logout',
  logoutConfirmation: 'Are you sure you want to logout?',
  passwordMismatch: 'Password and Confirm does not match',
};

export default strings;
