const strings = {
  myCashCoupon: 'My Cash Coupon',
  email: 'Email address',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  loginButton: 'Login',
  forgotPassword: 'Forgot password?',
  stillWithout: 'Still without account?',
  createOne: 'Create one',
  signup: 'Sign up',
  signupSubTitle: 'Start converting coupons to cash',
  name: 'Name',
  mobile: 'Mobile',
  username: 'User Name',
  alreadyAccount: 'I already have an account.',
  history: 'History',
  cashbackStores: 'Cashback Stores',
  balance: 'Balance',
  currentBalance: 'Current Balance',
  rs: '₹',
  welcomeBack: 'Welcome back to My Cash Coupon',
  withdraw: 'Withdraw',
  bankAccounts: 'Bank Accounts',
  topCashback: 'TOP Cashback Stores',
  invalidEmail: 'Please enter valid email',
  invalidName: 'Please enter Name',
  invalidUsername: 'Please enter Username',
  invalidPassword: 'Please enter password',
  invalidMobile: 'Please enter Mobile number',
  mobileLength: 'Please enter 10 digit Mobile number',
  cancel: 'Cancel',
  logout: 'Logout',
  logoutConfirmation: 'Are you sure you want to logout?',
  passwordMismatch: 'Password and Confirm does not match',
  couponScanHint: 'Please scan your coupon',
  cancel: 'Cancel',
  confirmCoupon: (coupon) => `Are you sure you want to add ${coupon} couponcode?`,
  ok: 'Ok',
  couponAdded: 'Coupon added successfully',
  notEnoughBalance: `You don't have enough balance`,
  invalidAmount: 'Please enter valid amount',
  withdrawalAmount: 'Withdrawal Amount',
  somethingWentWrong: 'Something went wrong, please try again after sometime',
  confirm: 'Confirm'
};

export default strings;
